import bootstrapBase from '../../../supabase/bootstrap.sql?raw'

export type SetupWizardInput = {
  orgName: string
  adminEmail: string
  departments: string[]
  accessMode: 'invite_only' | 'domain' | 'open'
  allowedDomain?: string
}

function slugify(label: string, index: number): string {
  return (
    label
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .replace(/^_|_$/g, '') || `dept_${index}`
  )
}

function sqlString(value: string): string {
  return value.replace(/'/g, "''")
}

export function buildOrgTail(input: SetupWizardInput): string {
  const deptRows = input.departments.map((label, index) => {
    const slug = slugify(label, index)
    return `    ('${slug}', '${sqlString(label)}', ${index})`
  })

  const adminSlugs = input.departments.map((label, index) => `'${slugify(label, index)}'`)
  const domainClause =
    input.accessMode === 'domain' && input.allowedDomain?.trim()
      ? `,\n  allowed_domain = '${sqlString(input.allowedDomain.trim())}'`
      : ''

  return `
-- ---------------------------------------------------------------------------
-- SupaSupport org customization (generated by supasupport.net/setup)
-- ---------------------------------------------------------------------------
UPDATE org_settings SET
  org_name = '${sqlString(input.orgName.trim())}',
  access_mode = '${input.accessMode}'${domainClause}
WHERE id = 1;

DELETE FROM departments;
INSERT INTO departments (slug, label, sort_order) VALUES
${deptRows.length ? deptRows.join(',\n') : "    ('general', 'General', 0)"};

INSERT INTO pending_members (email, role, department_slugs)
VALUES (
  lower(trim('${sqlString(input.adminEmail.trim())}')),
  'admin',
  ARRAY[${adminSlugs.length ? adminSlugs.join(', ') : "'general'"}]
);
`
}

export function buildFullBootstrapSql(input: SetupWizardInput): string {
  const header = `-- SupaSupport bootstrap for ${input.orgName.trim()}
-- Generated ${new Date().toISOString().slice(0, 10)} at supasupport.net/setup
-- Run this entire script once in Supabase → SQL Editor → New query → Run

`
  const trimmedBase = bootstrapBase.trimEnd()
  return `${header}${trimmedBase}\n${buildOrgTail(input)}`
}
